# - config -
#
# This file is the configuration for the webhook.
#
# Copyright (c) 2020 Prodex
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


#
# The secret key is a key which is used in order generate a signature.
# When the consumer receives the request, they apply the same algorithm
# that the provider does with the content and the secret they have on their end.
# If the signature they generate matches the one provided in the header,
# then they accept the request. Otherwise they reject it.
#
# We strongly recommend to pass the secret key to the server using environment variables.
# You can also generate a key using "ssh-keygen"
#

# Associate this key with your webhook in order to have secure endpoint.
secret_key: "AAAAB3NzaC1yc2EAAAADAQABAAACAQCW9x3I2gA6Uxd9BPEj"

#
# Customs keys.
# Add others secret keys for others endpoints in the webhook.
# Example with and endpoint : Just decorate the endpoint like this.
# @check_signature(secret_key=CONFIG_OBJ.get("my_key"))
#

# my_key: "custom_key"



# Timestamp
# Prevent the replay attack (https://en.wikipedia.org/wiki/Replay_attack)
timestamp_limit: 5000
